### ISSUE TITLE
翻译团队有交流群或者协作工具吗？GitHub 沟通不太方便。

### ISSUE THREAD

**Issue by mayneyao** [gatsbyjs/gatsby-zh-Hans#4]
@xiyizhou
  @nelsonkuang
  @QC-L
  @zhouyuexie

**Comment by zhouyuexie** [comment]
目前没有商定沟通工具，如果没有的话我推荐Telegram，刚刚建了一个Group，可以点击[Gatsby-Chinese-Translation](https://t.me/Gatsby-Chinese-Translation)加入。

**Comment by Pike96** [comment]
> 目前没有商定沟通工具，如果没有的话我推荐Telegram，刚刚建了一个Group，可以点击[Gatsby-Chinese-Translation](https://t.me/Gatsby-Chinese-Translation)加入。

你好，我也想加入翻译。
这个 Telegram group 我点开之后显示`Sorry, this user doesn't seem to exist.`
根据 [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#language-specific-maintainer-channels)的最后一部分，可以在Discord里建一个 `translation-zh-Hans`来交流

**Comment by zhouyuexie** [comment]
@Pike96 Telegram的限制问题，目前不知道如何解锁

Discord可以试一下，申请了一下创建一个channel，不过目前还没有回复

**Comment by mayneyao** [comment]
> > 目前没有商定沟通工具，如果没有的话我推荐Telegram，刚刚建了一个Group，可以点击[Gatsby-Chinese-Translation](https://t.me/Gatsby-Chinese-Translation)加入。
> 
> 你好，我也想加入翻译。
> 这个 Telegram group 我点开之后显示`Sorry, this user doesn't seem to exist.`
> ~根据 [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#language-specific-maintainer-channels) 的最后一部分，可以申请在 Discord 里建一个 `translation-zh-Hans` 频道来交流~
> 是不是国内上不了 Discord ？

我也遇到了这个问题，tg的链接无法加入。

> @Pike96 Telegram的限制问题，目前不知道如何解锁
> 
> Discord可以试一下，申请了一下创建一个channel，不过目前还没有回复

discord 可以，谁发个邀请链接

**Comment by zhouyuexie** [comment]
这是[加入链接](https://discord.gg/vv9yrcd)
